# Generated by Django 2.2.24 on 2021-09-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210928_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
